version: '3.8'

services:
  app:
    build: .
    container_name: ia-suporte
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
